//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue_C
    {
        public int Lib_Issue_Id { get; set; }
        public Nullable<int> Member_Id { get; set; }
        public Nullable<int> Book_No { get; set; }
        public Nullable<System.DateTime> Issue_date { get; set; }
        public Nullable<System.DateTime> Return_date { get; set; }
    
        public virtual Book_C Book_C { get; set; }
        public virtual Member_C Member_C { get; set; }
    }
}
