//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LibraryDB : DbContext
    {
        public LibraryDB()
            : base("name=LibraryDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Book_C> Book_C { get; set; }
        public virtual DbSet<Issue> Issues { get; set; }
        public virtual DbSet<Issue_C> Issue_C { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Member_C> Member_C { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<display> displays { get; set; }
        public virtual DbSet<view2> view2 { get; set; }
    
        [DbFunction("LibraryDB", "BookList")]
        public virtual IQueryable<BookList_Result> BookList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<BookList_Result>("[LibraryDB].[BookList]()");
        }
    
        public virtual int sp_UpdateMember(Nullable<int> p_memberid, string p_membername)
        {
            var p_memberidParameter = p_memberid.HasValue ?
                new ObjectParameter("p_memberid", p_memberid) :
                new ObjectParameter("p_memberid", typeof(int));
    
            var p_membernameParameter = p_membername != null ?
                new ObjectParameter("p_membername", p_membername) :
                new ObjectParameter("p_membername", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateMember", p_memberidParameter, p_membernameParameter);
        }
    
        public virtual int sp_deletebook(Nullable<int> bookno)
        {
            var booknoParameter = bookno.HasValue ?
                new ObjectParameter("bookno", bookno) :
                new ObjectParameter("bookno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_deletebook", booknoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_countbook(Nullable<int> bookno)
        {
            var booknoParameter = bookno.HasValue ?
                new ObjectParameter("bookno", bookno) :
                new ObjectParameter("bookno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_countbook", booknoParameter);
        }
    
        public virtual int sp_CountBooks(Nullable<int> cnt)
        {
            var cntParameter = cnt.HasValue ?
                new ObjectParameter("cnt", cnt) :
                new ObjectParameter("cnt", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CountBooks", cntParameter);
        }
    }
}
