//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class display
    {
        public decimal Lib_Issue_Id { get; set; }
        public string Book_Name { get; set; }
        public string Member_Name { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> Issue_date { get; set; }
    }
}
